export const ROLE_PERMISSIONS = {
  student: [
    "dashboard.view",
    "affiliate_profile.view",
    "research_projects.manage",
    "research_outputs.view",
    "awards_recognition.view",
    "my_submissions.view",
    "publications.manage",
    "program_dashboard.view",
  ],
  faculty: [
    "dashboard.view",
    "affiliate_profile.view",
    "research_projects.manage",
    "research_outputs.view",
    "awards_recognition.view",
    "my_submissions.view",
    "publications.manage",
    "program_dashboard.view",
  ],
  admin: [
    "dashboard.view",
    "affiliate_profile.view",
    "research_projects.manage",
    "research_outputs.view",
    "awards_recognition.view",
    "my_submissions.view",
    "publications.manage",
    "program_dashboard.view",
    "admin.review_queue.manage",
    "admin.controls.manage",
    "admin.users.manage",
    "admin.affiliates.manage",
    "admin.reports.view",
    "admin.audit.view",
  ],
};
